### ISSUE TITLE
https://arewee10syet.com is serving a certificate for arewewebextensionsyet.com, not arewee10syet.com

### ISSUE THREAD

**Issue by mozkeeler** [cpeterso/arewee10syet#11]
https://arewee10syet.com is serving a certificate for arewewebextensionsyet.com, not arewee10syet.com. I don't know if this is the right place to file this, but maybe @cpeterso will know?

**Comment by yfdyh000** [comment]
> Planning to retire this site
>By the time Firefox 57 comes out, all add-ons will be using WebExtensions, currently Firefox 55 is in Nightly. There isn't really much work being done on e10s for add-ons any more, all resources are focused on moving to WebExtensions. WebExtensions work in multi-process Firefox. As we get into the Firefox 56 cycle, this site will stop updating and be deleted not long after that.

**Comment by cpeterso** [comment]
AFAIK, @andymckay now maintains the arewee10syet.com and arewewebextensionsyet.com websites. Andy, does arewee10syet.com have its own HTTPS certificate? It looks like it is getting mixed up with arewewebextensionsyet.com's certificate.

**Comment by andymckay** [comment]
Oops, sorry. That's what I get for rushing something when I've got one foot out the door for a long weekend.

**Comment by cpeterso** [comment]
Thanks! The new arewee10syet.com certificate works for me now.
