### ISSUE TITLE
detect browser's plugins

### ISSUE THREAD

**Issue by jayenashar** [cpeterso/arewee10syet#8]
can you use window.navigator.plugins and put the visitors plugins at the top of the list?

**Comment by cpeterso** [comment]
Thanks for the suggestion, Jayen. We only plan to track compatibility for Firefox extensions (add-ons) on this website, not NPAPI plugins like Flash or Silverlight. While JavaScript can detect which NPAPI plugins are installed in navigator.plugins, there is no way for JavaScript to detect which Firefox extensions a user has installed.

**Comment by jayenashar** [comment]
very informative.  thanks!  can you open about:addons in an iframe?  or do you have any influence over the display in about:addons so bugs & it works can be reported straight from there?

**Comment by cpeterso** [comment]
I don't think you can load any about: pages in an iframe because they have special privileges in Firefox.
