### ISSUE TITLE
No ways to request add new items

### ISSUE THREAD

**Issue by yfdyh000** [cpeterso/arewee10syet#9]
For example, a request box to generate the mailto link.

**Comment by cpeterso** [comment]
@yfdyh000, the website dynamically loads the list of add-ons from a Google spreadsheet. There is no need to create mailto links for new add-ons by hand. :-)

If you email me at cpeterson at mozilla dot com, I share more information about the add-on spreadsheet.

**Comment by tracywalker** [comment]
I added Greasy Scripts to the spreadsheet this morning.

**Comment by yfdyh000** [comment]
I mean that an input box and dynamically generate a mailto link to report.
I hope this list can be more comprehensive to facilitate reports.
